//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_Radnih_Sati
{
    using System;
    using System.Collections.Generic;
    
    public partial class Djelatnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Djelatnik()
        {
            this.Projekts = new HashSet<Projekt>();
            this.Projekt_Djelatnik = new HashSet<Projekt_Djelatnik>();
            this.SatiProjekts = new HashSet<SatiProjekt>();
            this.Tims = new HashSet<Tim>();
            this.LoginDjelatniks = new HashSet<LoginDjelatnik>();
        }
    
        public int IDDjelatnik { get; set; }
        public int TipID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public System.DateTime DatumZaposlenja { get; set; }
        public int TimID { get; set; }
        public Nullable<bool> Aktivnost { get; set; }
    
        public virtual Tim Tim { get; set; }
        public virtual TipDjelatnika TipDjelatnika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekt> Projekts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekt_Djelatnik> Projekt_Djelatnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatiProjekt> SatiProjekts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tim> Tims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginDjelatnik> LoginDjelatniks { get; set; }
    }
}
