//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_Radnih_Sati
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDjelatnik
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int DjelatnikID { get; set; }
    
        public virtual Djelatnik Djelatnik { get; set; }
    }
}
