//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_Radnih_Sati
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt_Tim
    {
        public int IDProjektTim { get; set; }
        public int ProjektID { get; set; }
        public int TimID { get; set; }
    
        public virtual Projekt Projekt { get; set; }
        public virtual Tim Tim { get; set; }
    }
}
