//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_Radnih_Sati
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekt()
        {
            this.Projekt_Djelatnik = new HashSet<Projekt_Djelatnik>();
            this.Projekt_Klijent = new HashSet<Projekt_Klijent>();
            this.Projekt_Tim = new HashSet<Projekt_Tim>();
            this.SatiProjekts = new HashSet<SatiProjekt>();
        }
    
        public int IDProjekt { get; set; }
        public string Naziv { get; set; }
        public System.DateTime DatumOtvaranja { get; set; }
        public Nullable<int> VoditeljID { get; set; }
        public Nullable<int> KlijentID { get; set; }
        public Nullable<bool> Aktivnost { get; set; }
    
        public virtual Djelatnik Djelatnik { get; set; }
        public virtual Klijent Klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekt_Djelatnik> Projekt_Djelatnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekt_Klijent> Projekt_Klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekt_Tim> Projekt_Tim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatiProjekt> SatiProjekts { get; set; }
    }
}
