//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencija_Radnih_Sati
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tim()
        {
            this.Djelatniks = new HashSet<Djelatnik>();
            this.Projekt_Tim = new HashSet<Projekt_Tim>();
        }
    
        public int IDTim { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> VoditeljID { get; set; }
        public Nullable<bool> Aktivnost { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Djelatnik> Djelatniks { get; set; }
        public virtual Djelatnik Djelatnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekt_Tim> Projekt_Tim { get; set; }
    }
}
